name: hydro-ml
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.14
  - numpy>=1.24
  - scipy>=1.10
  - pytorch>=2.1
  - torch-geometric>=2.5
  - pyyaml>=6.0
  - matplotlib>=3.7
  - tensorboard>=2.15
  - libmobility
  - cuda-cudart-dev
  - cuda-nvcc
  - pip
  - pip:
      - pytorch-lightning>=2.1
      - torchmd-net>=2.6
