[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "hydro-ml"
version = "0.1.0"
description = "ML for Hydrodynamics: Generalization Across Multiple Geometries"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
include = ["data*", "models*", "evaluation*", "utils*"]
