model_cfg: !!python/object:utils.config.ModelConfig
  cutoff_radius: 30.0
  distance_influence: both
  equivariance_invariance_group: O(3)
  hidden_dim: 128
  hydrodynamic_radius: 1.0
  input_dim: 3
  max_num_neighbors: 128
  model_type: torchmd_tn
  neighbor_strategy: brute
  num_heads: 8
  num_layers: 2
  num_rbf: 32
  output_dim: 3
  rbf_type: expnorm
  trainable_rbf: true
  viscosity: 0.05305164769729845
train_cfg: !!python/object:utils.config.TrainingConfig
  batch_size: 64
  gradient_clip: 1.0
  learning_rate: 0.0001
  loss_type: mse
  max_epochs: 500
  passive_weight: 1.0
  patience: 80
  precision: 32-true
  relative_loss_eps: 0.01
  seed: 42
  weight_decay: 0.0001
